#!/bin/sh
base=$1
if [ "x$base" = "x" ]; then
  echo "Usage: $? <directory>"
  echo "directory contains many csv file generated by kubectl_mon.py."
  exit 1
fi
cd $base
ls *.out | while read file; do
  grep minion all-nodes.out >$file.csv
  sed -i '/ErrImagePull/d' $file.csv
  sed -i '/resources/d' $file.csv
  ../pod_stats.py $file.csv
done

