#!/bin/sh
base=$PWD
arg="$1"
ls $arg &>/dev/null
if [ $? -ne 0 ]; then
  echo "file or directory not provided. exit"
  echo "Usage: $? <directory>|testfile.out"
  echo "directory contains many csv file generated by kubectl_mon.py."
  exit 1
fi

gen(){
  file=$1
  prefix="Tring generate graph from $file... "
  file $file | grep empty >/dev/null
  if [ $? -eq 0 ]; then
    echo "$prefix file is empty"
    return
  fi
  grep minion $file >$file.csv
  sed -i '/ErrImagePull/d' $file.csv
  sed -i '/resources/d' $file.csv
  sed -i '/-ting/d' $file.csv
  sed -i '$ d' $file.csv
  $base/pod_stats.py $file.csv
  rm $file.csv
  echo "$prefix ok"
}

datadir=$1
if [ ! -d $arg ]; then
  gen $arg
  exit
else
  datadir=$arg
fi

cd $datadir
ls *.out | while read l; do
  gen $l
done

