apiVersion: v1
kind: Service
metadata:
  name: fs
  #namespace: qb-pro
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 8080
  selector:
    app: fs
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fs
  #namespace: qb-pro
  labels:
    app: fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: fs
          image: reg.qianbao-inc.com/k8s-monitoring/fs
          ports:
          - containerPort: 8000
