apiVersion: v1
kind: Pod
metadata:
  name: metrics
spec: 
  containers:
  - name: metrics
    image: harbor.wk.qianbao-inc.com/tools/netshoot 
    command: [ "/bin/sh", "-c", "curl -s http://issue.qianbao-inc.com/SRE/k8s/raw/branch/master/testing/metrics/podmetrics.sh | sh" ]
