# for prometheus at expe environment, version 2.2.1

global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
rule_files:
  - "/etc/prometheus-rules/*.rules"
scrape_configs:

  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L19
  - job_name: 'kubernetes-apiservers'

    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    kubernetes_sd_configs:
      - role: endpoints
        api_server: https://172.28.40.251:6443
        tls_config:
          insecure_skip_verify: true
        bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https


  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L37
  - job_name: 'kubernetes-nodes'
    scheme: http
    kubernetes_sd_configs:
      - role: node
        api_server: http://172.28.40.251:8080
        tls_config:
          insecure_skip_verify: true
        bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:10255'
        target_label: __address__

  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L79
  - job_name: 'kubernetes-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
        api_server: http://172.28.40.251:8080
        tls_config:
          insecure_skip_verify: true
        bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name

  - job_name: kubernetes-dns
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: [kube-system]
        api_server: http://172.28.40.251:8080
        tls_config:
          insecure_skip_verify: true
        bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*):(1005[4|5])
      target_label: __address__
      replacement: ${1}:${2}
      action: keep

  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L119
  - job_name: 'kubernetes-services'
    scheme: http
    metrics_path: /probe
    params:
      module: [http_2xx]
    kubernetes_sd_configs:
      - role: service
        api_server: http://172.28.40.251:8080
        tls_config:
          insecure_skip_verify: true
        bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
        action: keep
        regex: true
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: kubernetes_name

  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L156
  - job_name: 'kubernetes-pods'
    scheme: http
    kubernetes_sd_configs:
      - role: pod
        api_server: http://172.28.40.251:8080
        tls_config:
          insecure_skip_verify: true
        bearer_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtazhzLXRva2VuLW5ma3NsIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMtazhzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTY4MGJhYTYtMzRiZi0xMWU4LTk4NTItYzg1Yjc2YWYzYTE5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om1vbml0b3Jpbmc6cHJvbWV0aGV1cy1rOHMifQ.bf56-DcjrjDDp15pcs4q2TmwRnyyD8db6-j61DnjalssqhU3pehQIes6krmEJiSHFIRCz8Y4nUCyBYRE8MJNp7jL27kDn5S4h7GwRVigmBc8aQPG7izmo_jYQYFNI7FcuOkvjs3m5gRzifRF-LhaqWbgF49xCn1d5rTVoQA_b0bvVuFurUmus-QsQXIUoGQ4AgKbtGfdagVb6cVE5kr60jFVUFI9IlnfB7sOGisGyRfYe3Lm4rOSNz-Bxli5znZc0IqdPLlECbJWFLSxgk0es5LLZVHK_LlxVb9sfbJqX8sqVyIPNUVMPWP73tDeVq4p8wvT6Jh6pO26x58Y7J0bgQ"
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 9\d{3}

  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
